[[constraint]]
  name = "github.com/vmware-tanzu/velero"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/satori/uuid"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
